import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import LandingImage from "../components/LandingImage";


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>My Medium Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        <LandingImage/>


    </div>
  )
}

export default Home
